# Generated by Django 4.2.7 on 2023-12-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id_game', models.IntegerField(max_length=6, primary_key=True, serialize=False, verbose_name='Id Game')),
                ('title', models.CharField(max_length=80, verbose_name='Titulo')),
                ('release_date', models.DateField(null=True, verbose_name='Fecha de lanzamiento')),
                ('developer', models.CharField(max_length=50, null=True, verbose_name='Desarollador')),
            ],
        ),
    ]
