# Generated by Django 4.2.7 on 2023-12-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_games_id_game_games_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='banner',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Portada'),
        ),
    ]
