# Generated by Django 4.2.7 on 2023-12-06 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_games_banner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
